### ISSUE TITLE
No such module 'CoreAudio.CoreAudioTypes' in Catalina/XCode 11.4

### ISSUE THREAD

**Issue by ikester** [lvsti/Audit#1]
I just discovered your audio- and video-related repos. Cool stuff! Thanks for sharing.

I tried building Audit on my Mac running Catalina (10.15.4) and XCode 11.4 and the build failed with:
`No such module 'CoreAudio.CoreAudioTypes'` 

For `AudioChannelLayout.swift`.

Changing the import statement to:
`import CoreAudioTypes`

fixes the problem and allow the build to succeed. I didn't create a pull request because I have no idea how this change affects previous versions of MacOS/Xcode.

I found other issues trying to click on an item in the TableView but I'll open a separate issue if I figure out what's wrong.

**Comment by lvsti** [comment]
Hi, thanks for the report, I pushed the fix to master, let me know if it works for you.
