### ISSUE TITLE
Why Break points are not hitting?

### ISSUE THREAD

**Issue by Raj123456788** [lvsti/Audit#2]
Hello,
I tried to debug a plugin using Audit. it does not work? Can't I debug this like a core media IO DAL video plugin?

**Comment by lvsti** [comment]
If your question is, is Audit exercising the HAL plugins the same way as Cameo does (i.e. by opening a camera window for the selected plugin), then the answer is no.

**Comment by Raj123456788** [comment]
Can you recommend me any HAL plugins and how to debug?

**Comment by Raj123456788** [comment]
This is the only way for now https://github.com/kyleneideck/BackgroundMusic/blob/master/DEVELOPING.md#building-and-debugging
